# Generated by Django 5.1.7 on 2025-07-30 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('OC', 'Oceania'), ('AN', 'Antarctica')], max_length=200)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.CharField(max_length=200)),
                ('pod', models.CharField(max_length=200)),
                ('internship', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('skills', models.TextField()),
                ('additional_info', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the organization (e.g., FinTech Nexus, Google, Y Combinator)', max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(blank=True, choices=[('CO', 'Company'), ('EV', 'Event/Conference'), ('CM', 'Professional Community'), ('AC', 'Accelerator/Incubator'), ('NP', 'Non-Profit Organization'), ('UN', 'University/Academic Institution'), ('UN', 'Other')], max_length=2, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the organization, its mission, or purpose.', null=True)),
                ('website', models.URLField(blank=True, max_length=2083, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('link', models.URLField(max_length=2083)),
                ('platform', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Your role or title (e.g., Software Engineer, Attendee, Cohort Member)', max_length=255, null=True)),
                ('experience_type', models.CharField(choices=[('EM', 'Employment (Full/Part-time)'), ('IN', 'Internship'), ('VO', 'Volunteer'), ('AC', 'Academic (e.g., Research/Teaching Assistant)'), ('FR', 'Freelance/Contract'), ('BM', 'Board Member'), ('ME', 'Mentor'), ('AD', 'Advisor'), ('AT', 'Event Attendee'), ('CM', 'Program/Cohort Member'), ('FO', 'Founder'), ('CP', 'Competition Participant'), ('OT', 'Other')], help_text='The nature of your involvement with this organization.', max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Describe your responsibilities, achievements, or what you learned/contributed.', null=True)),
                ('network_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='network.networkmember')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_people', to='network.organization')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('type', models.CharField(choices=[('ST', 'Startup'), ('NP', 'Non Profit')], max_length=5)),
                ('stage', models.CharField(choices=[('J', 'Just an idea'), ('MVP', 'Research/MVP/Early Development'), ('L', 'Launched Venture')], max_length=5)),
                ('what_are_they_looking_for', models.TextField()),
                ('additional_info', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('founders', models.ManyToManyField(to='network.networkmember')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(max_length=2083)),
                ('platform', models.CharField(blank=True, max_length=200, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='network.project')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(max_length=2083)),
                ('description', models.TextField()),
                ('platform', models.CharField(blank=True, max_length=200, null=True)),
                ('network_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='network.networkmember')),
            ],
        ),
    ]
