# Generated by Django 5.1.7 on 2025-07-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_networkmember_additional_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('filter', 'Filter Search'), ('smart', 'Smart Search')], max_length=10)),
                ('query', models.TextField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
